"""Prepare ShipRSImageNet V1 for single-class ship detection (YOLO format).

Reads the ShipRSImageNet_V1.zip COCO-format level_0 annotations, filters to the
"Ship" class (Dock annotations become background), converts boxes to normalized
YOLO format, extracts the relevant images straight from the zip into a YOLO
directory layout, validates every box, and writes an ultralytics dataset YAML.

Protocol note: ShipRSImageNet's official `test` split ships images only (labels
withheld for benchmarking), so we train on the official `train` split and report
detection metrics on the official `val` split, which is how the dataset is used
in the literature. The `test` images are extracted unlabeled for qualitative demos.

Usage:
    python scripts/prepare_shiprs.py
    python scripts/prepare_shiprs.py --zip data/ShipRSImageNet_V1.zip --out data/yolo
"""

from __future__ import annotations

import argparse
import json
import zipfile
from collections import Counter
from pathlib import Path

ZIP_INNER_COCO = "ShipRSImageNet_V1/COCO_Format/ShipRSImageNet_bbox_{split}_level_0.json"
ZIP_INNER_IMAGES = "ShipRSImageNet_V1/VOC_Format/JPEGImages/{file_name}"
SHIP_CLASS_NAME = "Ship"
# COCO area thresholds (in pixels^2) for small/medium/large stratification.
AREA_SMALL = 32 * 32
AREA_LARGE = 96 * 96


def _load_coco(zf: zipfile.ZipFile, split: str) -> dict:
    with zf.open(ZIP_INNER_COCO.format(split=split)) as f:
        return json.load(f)


def _ship_category_id(coco: dict) -> int:
    for c in coco["categories"]:
        if c["name"] == SHIP_CLASS_NAME:
            return c["id"]
    raise ValueError(f"'{SHIP_CLASS_NAME}' category not found in {[c['name'] for c in coco['categories']]}")


def convert_split(zf: zipfile.ZipFile, split: str, out: Path) -> dict:
    """Convert one split; returns a stats dict for the validation report."""
    coco = _load_coco(zf, split)
    ship_id = _ship_category_id(coco)

    images = {img["id"]: img for img in coco["images"]}
    boxes_by_image: dict[int, list] = {iid: [] for iid in images}
    has_annotations = "annotations" in coco
    for ann in coco.get("annotations", []):
        if ann["category_id"] != ship_id:
            continue
        boxes_by_image[ann["image_id"]].append(ann)

    img_dir = out / "images" / split
    lbl_dir = out / "labels" / split
    img_dir.mkdir(parents=True, exist_ok=True)
    lbl_dir.mkdir(parents=True, exist_ok=True)

    stats = {
        "split": split,
        "labeled": has_annotations,
        "n_images": len(images),
        "n_with_ships": 0,
        "n_background": 0,
        "n_boxes": 0,
        "n_clipped": 0,
        "n_degenerate": 0,
        "area_buckets": Counter(),
    }

    for iid, img in images.items():
        fn = img["file_name"]
        w, h = float(img["width"]), float(img["height"])
        # Extract the image straight from the zip (no intermediate full extraction).
        with zf.open(ZIP_INNER_IMAGES.format(file_name=fn)) as src:
            (img_dir / fn).write_bytes(src.read())

        lines = []
        for ann in boxes_by_image.get(iid, []):
            x, y, bw, bh = ann["bbox"]
            if bw <= 0 or bh <= 0:
                stats["n_degenerate"] += 1
                continue
            # area stratification on the raw pixel box
            area = bw * bh
            if area < AREA_SMALL:
                stats["area_buckets"]["small"] += 1
            elif area > AREA_LARGE:
                stats["area_buckets"]["large"] += 1
            else:
                stats["area_buckets"]["medium"] += 1

            cx, cy, nw, nh = (x + bw / 2) / w, (y + bh / 2) / h, bw / w, bh / h
            clipped = False
            vals = []
            for v in (cx, cy, nw, nh):
                cv = min(max(v, 0.0), 1.0)
                if cv != v:
                    clipped = True
                vals.append(cv)
            if clipped:
                stats["n_clipped"] += 1
            lines.append(f"0 {vals[0]:.6f} {vals[1]:.6f} {vals[2]:.6f} {vals[3]:.6f}")

        # Empty label file = background image (ultralytics convention).
        (lbl_dir / f"{Path(fn).stem}.txt").write_text("\n".join(lines))
        stats["n_boxes"] += len(lines)
        if lines:
            stats["n_with_ships"] += 1
        else:
            stats["n_background"] += 1

    return stats


def write_yaml(out: Path) -> Path:
    yaml_path = out / "shiprs.yaml"
    yaml_path.write_text(
        f"# ShipRSImageNet V1 - single-class ship detection\n"
        f"# Auto-generated by scripts/prepare_shiprs.py. Do not edit by hand.\n"
        f"path: {out.resolve().as_posix()}\n"
        f"train: images/train\n"
        f"val: images/val\n"
        f"names:\n  0: ship\n"
    )
    return yaml_path


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--zip", default="data/ShipRSImageNet_V1.zip")
    ap.add_argument("--out", default="data/yolo")
    ap.add_argument("--splits", nargs="+", default=["train", "val", "test"])
    args = ap.parse_args()

    out = Path(args.out)
    with zipfile.ZipFile(args.zip) as zf:
        all_stats = [convert_split(zf, s, out) for s in args.splits]
    yaml_path = write_yaml(out)

    print("\n=== ShipRSImageNet -> YOLO conversion report ===")
    for s in all_stats:
        ab = s["area_buckets"]
        label_flag = "labeled" if s["labeled"] else "UNLABELED (test, withheld)"
        print(
            f"[{s['split']:5s}] {label_flag}: images={s['n_images']} "
            f"with_ships={s['n_with_ships']} background={s['n_background']} "
            f"boxes={s['n_boxes']} "
            f"(small={ab['small']} medium={ab['medium']} large={ab['large']}) "
            f"clipped={s['n_clipped']} degenerate={s['n_degenerate']}"
        )
    # Validation assertions: no degenerate boxes should slip through, every
    # labeled split must have boxes, normalized coords are guaranteed in-range
    # by construction (clipping is logged, not silently dropped).
    for s in all_stats:
        if s["labeled"]:
            assert s["n_boxes"] > 0, f"{s['split']} produced zero boxes"
    print(f"\nWrote dataset YAML -> {yaml_path}")
    print("Validation OK: all normalized coords in [0,1]; clipped boxes logged above.")


if __name__ == "__main__":
    main()
